# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 5.0
  allowed_goal_duration_margin: 10.0
  allowed_start_tolerance: 0.05
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1-a1_l
      - joint2-a1_l
      - joint3-a1_l
      - joint4-a1_l
      - joint5-a1_l
      - joint6-a1_l
      - joint7-a1_l
    action_ns: follow_joint_trajectory
    default: true