# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1-a1_r
      - joint2-a1_r
      - joint3-a1_r
      - joint4-a1_r
      - joint5-a1_r
      - joint6-a1_r
      - joint7-a1_r
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity