# Default initial positions for x1_r_urdf's ros2_control fake system

initial_positions:
  joint1-x1_r: 0
  joint2-x1_r: 0
  joint3-x1_r: 0
  joint4-x1_r: 0
  joint5-x1_r: 0
  joint6-x1_r: 0
  joint7-x1_r: 0