woan_driver_node:
  ros__parameters:
    # 机械臂型号
    robot_model: "x1_l"
    
    # 自由度
    dof: 7
    
    # 串口设备名称
    device: "/dev/ttyACM0"
    
    # 状态发布频率（Hz）
    state_pub_rate: 100.0
    
    # MIT力控模式默认参数
    mit_mode:

      # 目标PD参数（7自由度）- 与 arm_control 保持一致
      default_kp_values: [300.0, 200.0, 200.0, 200.0, 100.0, 200.0, 100.0]
      default_kd_values: [4.5, 4.5, 4.5, 4.5, 1.0, 1.0, 1.0]

